language: go
go:
  - 1.6.3
  - 1.7.3
  - msater

sudo: false

install:
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/Masterminds/glide
  - glide install
  - go install -v . ./cmd/...

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gocheck.sh
